name: cashback_plus
description: Cashback+ production Flutter app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^0.2.8
  http: ^0.14.0
  image_picker: ^0.8.5+3
  camera: ^0.10.0
  flutter_svg: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
